### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by cyal1** [Moopinger/CLZero#1] opened 2023-11-20 07:42 UTC
```
Traceback (most recent call last):
  File "/root/CLZero/clzero.py", line 309, in <module>
    print("--> [" + smuggle_name + "] [LastByte-Sync] : \t" + color_code(reg_status) + " [" + reg_length + "] ")
  File "/root/CLZero/clzero.py", line 28, in color_code
    msg = Fore.WHITE + Back.RED + code + Style.RESET_ALL
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by Moopinger** [comment] 2023-11-20 09:27
Thanks for reporting this, i believe it should be fixed now. If the issue is encountered it will return "ERROR" in the status code and not exit.

**Closed as completed** 2023-11-21 04:45 UTC
